// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package COEN;

/************************************************************/
/**
 * 
 */
public class Admin {
	/**
	 * 
	 */
	public void addFlight() {
	}

	/**
	 * 
	 * @param flightNo 
	 */
	public void modifyFlight(int flightNo) {
	}

	/**
	 * 
	 * @param flightNo 
	 */
	public void cancelFlight(int flightNo) {
	}
};
