// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package COEN;

/************************************************************/
/**
 * 
 */
public class Agent extends User {
	/**
	 * 
	 */
	public String companyName;
};
