// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package COEN;

/************************************************************/
/**
 * 
 */
public class Booking {
	/**
	 * 
	 */
	private int bookingID;
	/**
	 * 
	 */
	private int flightNo;
	/**
	 * 
	 */
	private String destination;
	/**
	 * 
	 */
	private String source;
	/**
	 * 
	 */
	private String departureDate;
	/**
	 * 
	 */
	private String departureTime;

	/**
	 * 
	 * @param bookingID 
	 */
	public void cancelBooking(String bookingID) {
	}

	/**
	 * 
	 * @param bookingID 
	 */
	public void modifyBooking(String bookingID) {
	}
};
