// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package COEN;

/************************************************************/
/**
 * 
 */
public class Customer extends User {
	/**
	 * 
	 */
	private Bookings bookingPlanned;

	/**
	 * 
	 * @return 
	 */
	public Bookings setListOfBooking() {
	}

	/**
	 * 
	 * @return 
	 */
	public Bookings getListOfBooking() {
	}
};
