// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package COEN;

/************************************************************/
/**
 * 
 */
public class Flight {
	/**
	 * 
	 */
	private int bookingID;
	/**
	 * 
	 */
	private int flightNo;
	/**
	 * 
	 */
	private String destination;
	/**
	 * 
	 */
	private String departureTime;
	/**
	 * 
	 */
	private String source;
	/**
	 * 
	 */
	private String arrivalTime;
	/**
	 * 
	 */
	public Admin[] admin;
};
