// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package COEN;

/************************************************************/
/**
 * 
 */
public class Payment extends Transaction {
	/**
	 * 
	 */
	private int paymentMade;

	/**
	 * 
	 */
	public void pay() {
	}
};
