// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package COEN;

/************************************************************/
/**
 * 
 */
public class Refund extends Transaction {
	/**
	 * 
	 */
	private int refundGenerated;

	/**
	 * 
	 */
	public void refund() {
	}
};
