// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package COEN;

/************************************************************/
/**
 * 
 */
public class register {
	/**
	 * 
	 */
	public User user;

	/**
	 * 
	 * @param  
	 * @return 
	 */
	public User createUser(String[] null) {
	}
};
