// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package COEN;

/************************************************************/
/**
 * 
 */
public class Schedule {
	/**
	 * 
	 */
	private Flight listOfFlights;
	/**
	 * 
	 */
	public Bookings[] bookings;

	/**
	 * 
	 * @return 
	 */
	public Flight getFlights() {
	}

	/**
	 * 
	 * @param source 
	 * @param destination 
	 * @param date 
	 */
	private void setListOfFlights(String source, String destination, EcorePrimitiveTypes.EDate date) {
	}
};
