// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package COEN;

/************************************************************/
/**
 * 
 */
abstract class User {
	/**
	 * 
	 */
	private int[] ID;
	/**
	 * 
	 */
	public String firstName;
	/**
	 * 
	 */
	public String lastName;
	/**
	 * 
	 */
	public String gender;
	/**
	 * 
	 */
	public String password;
	/**
	 * 
	 */
	public String username;

	/**
	 * 
	 * @param username 
	 * @param password 
	 * @return 
	 */
	public boolean login(String username, String password) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean logout() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean createBooking() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean updatePassword() {
	}
};
