// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package COEN;

/************************************************************/
/**
 * 
 */
abstract class User {
	/**
	 * 
	 */
	private int[] ID;
	/**
	 * 
	 */
	private String firstName;
	/**
	 * 
	 */
	private String lastName;
	/**
	 * 
	 */
	private String gender;
	/**
	 * 
	 */
	private String password;
	/**
	 * 
	 */
	private String username;
	/**
	 * 
	 */
	public register[] register;
	/**
	 * 
	 */
	public Booking[] bookings;

	/**
	 * 
	 * @param username 
	 * @param password 
	 * @return 
	 */
	public boolean login(String username, String password) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean logout() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean createBooking() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean updatePassword() {
	}
};
